### ISSUE TITLE
无法查询到uid

### ISSUE THREAD

**Issue by Tinhone** [Rsplwe/karyl-project#1]
av900044662
![图片](https://user-images.githubusercontent.com/81268244/188068726-28bea631-4f2d-4bc3-98ff-2245dae1edd4.png)
点击查看按钮后，没有显示uid

弹幕内容：
蜥蜴和猫的混杂体。产生大脑突变。产生了自我意识和什么的就产生人类文明。猫不是看你的丑。猫其实看你是同类。是突变的。

在该视频中可以看到此人共发了6条弹幕：
![图片](https://user-images.githubusercontent.com/81268244/188069077-71974906-9a35-457b-8540-beb37fa6dd74.png)

屏蔽用户后显示：
![图片](https://user-images.githubusercontent.com/81268244/188069139-240d0182-d42d-44a2-a59b-3e2b512b5cfb.png)

**Comment by Rsplwe** [comment]
受限于计算能力，uid > 20 亿的弹幕可能不会显示

**Comment by Tinhone** [comment]
> 受限于计算能力，uid > 20 亿的弹幕可能不会显示

想问一下，有可能将计算交给用户进行吗？

**Comment by Rsplwe** [comment]
> > 受限于计算能力，uid > 20 亿的弹幕可能不会显示
> 
> 想问一下，有可能将计算交给用户进行吗？

计算本身就是在客户端进行的，如果要修改的话，可以更改 https://github.com/Rsplwe/karyl-project/blob/main/src/utils/Crc32.ts#L136 的 `2000000`

**Comment by Tinhone** [comment]
> > > 受限于计算能力，uid > 20 亿的弹幕可能不会显示
> > 
> > 
> > 想问一下，有可能将计算交给用户进行吗？
> 
> 计算本身就是在客户端进行的，如果要修改的话，可以更改 https://github.com/Rsplwe/karyl-project/blob/main/src/utils/Crc32.ts#L136 的 `2000000` 为其他数字，例如更改为 `3000000` 即为 30 亿内的UID范围

唔哦，原来是这样，如果能够更新一下就太好啦

**Comment by Tinhone** [comment]
> > > 受限于计算能力，uid > 20 亿的弹幕可能不会显示
> > 
> > 
> > 想问一下，有可能将计算交给用户进行吗？
> 
> 计算本身就是在客户端进行的，如果要修改的话，可以更改 https://github.com/Rsplwe/karyl-project/blob/main/src/utils/Crc32.ts#L136 的 `2000000` 为其他数字，例如更改为 `3000000` 即为 30 亿内的UID范围

唔哦，原来是这样，如果能够更新一下就太好啦

作者大大辛苦了！
